/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bao;
import model.Sach;
import service.Service;

/**
 *
 * @author Admin
 */
public class ListSach extends javax.swing.JFrame {
    Service service;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form ListSach
     */
    public ListSach() {
        service = new Service();
        initComponents();
        
        
        ///Tranh nguoi dung sua du lieu
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        TableSach.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("MaSach");
        defaultTableModel.addColumn("TenSach");
        defaultTableModel.addColumn("TenTacGia");
        defaultTableModel.addColumn("TenNXB");
        defaultTableModel.addColumn("SoBPH");
        defaultTableModel.addColumn("SoTrang");
        
        List<Sach> sach = service.getALLSACH();
        for(Sach sachs : sach){
            defaultTableModel.addRow(new Object[]{sachs.getMaSach(), sachs.getTenSach(),sachs.getTenTGS(),sachs.gettenNXBS(),sachs.getsoBPHS(),sachs.getsoTrangS()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        BtnThemSach = new javax.swing.JButton();
        BtnSuaSach = new javax.swing.JButton();
        BtnXoaSach = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        BtnBackSach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("UTM Akashi", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý sách");

        TableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableSach);

        BtnThemSach.setText("Thêm");
        BtnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemSachActionPerformed(evt);
            }
        });

        BtnSuaSach.setText("Sửa");

        BtnXoaSach.setText("Xóa");
        BtnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaSachActionPerformed(evt);
            }
        });

        BtnRefresh.setText("Refresh");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });

        BtnBackSach.setText("Quay lại");
        BtnBackSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBackSach, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBackSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackSachActionPerformed
        // TODO add your handling code here:
        new TuyChon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackSachActionPerformed

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<Sach> sach = service.getALLSACH();
        for(Sach sachs : sach){
            defaultTableModel.addRow(new Object[]{sachs.getMaSach(), sachs.getTenSach(),sachs.getTenTGS(),sachs.gettenNXBS(),sachs.getsoBPHS(),sachs.getsoTrangS()});
        }
    }//GEN-LAST:event_BtnRefreshActionPerformed

    private void BtnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemSachActionPerformed
        // TODO add your handling code here:
        new ThemSach().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnThemSachActionPerformed

    private void BtnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaSachActionPerformed
        // TODO add your handling code here:
        int row = TableSach.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(ListSach.this, "Vui long chon hoc sinh truoc", "loi",JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm = JOptionPane.showConfirmDialog(ListSach.this,"Ban chac chan muon xoa khong");
            
            if(confirm == JOptionPane.YES_OPTION){
                String MaSach = String.valueOf(TableSach.getValueAt(row, 0));
                
                service.deleteSach(MaSach);
            
                
             /// Xoa xong rooif refresh
            defaultTableModel.setRowCount(0);
            List<Sach> sach = service.getALLSACH();
            for(Sach sachs : sach){
            defaultTableModel.addRow(new Object[]{sachs.getMaSach(), sachs.getTenSach(),sachs.getTenTGS(),sachs.gettenNXBS(),sachs.getsoBPHS(),sachs.getsoTrangS()});
        }
            }
        }
    }//GEN-LAST:event_BtnXoaSachActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBackSach;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSuaSach;
    private javax.swing.JButton BtnThemSach;
    private javax.swing.JButton BtnXoaSach;
    private javax.swing.JTable TableSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
