/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bao;
import model.thuVien;
import service.Service;

/**
 *
 * @author Admin
 */
public class ListTapChi extends javax.swing.JFrame {
    Service service;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form ListTapChi
     */
    public ListTapChi() {
        service = new Service();
        initComponents();
        
        ///Tranh nguoi dung sua du lieu
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        TableTapChi.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("MaTC");
        defaultTableModel.addColumn("TenTC");
        defaultTableModel.addColumn("TenNXB");
        defaultTableModel.addColumn("SoBPH");
        defaultTableModel.addColumn("SoPH");
        defaultTableModel.addColumn("ThangPH");
        
        List<thuVien> tapchi = service.getALLTapChi();
        for(thuVien Tapchis : tapchi){
            defaultTableModel.addRow(new Object[]{Tapchis.getMaTC(), Tapchis.getTenTC(),Tapchis.gettenNXBTC(), Tapchis.getSoBPHTC(),Tapchis.getSoPHTC(),Tapchis.getThangPHTC()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnXoaTapChi = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTapChi = new javax.swing.JTable();
        BtnThemTapChi = new javax.swing.JButton();
        BtnSuaTapChi = new javax.swing.JButton();
        BtnBackTapChi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnXoaTapChi.setText("Xóa");
        BtnXoaTapChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaTapChiActionPerformed(evt);
            }
        });

        BtnRefresh.setText("Refresh");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("UTM Akashi", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý tạp chí");

        TableTapChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableTapChi);

        BtnThemTapChi.setText("Thêm");
        BtnThemTapChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemTapChiActionPerformed(evt);
            }
        });

        BtnSuaTapChi.setText("Sửa");

        BtnBackTapChi.setText("Quay lại");
        BtnBackTapChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackTapChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnThemTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSuaTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnXoaTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBackTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThemTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSuaTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXoaTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBackTapChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackTapChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackTapChiActionPerformed
        // TODO add your handling code here:
        new TuyChon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackTapChiActionPerformed

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<thuVien> tapchi = service.getALLTapChi();
        for(thuVien Tapchis : tapchi){
            defaultTableModel.addRow(new Object[]{Tapchis.getMaTC(), Tapchis.getTenTC(),Tapchis.gettenNXBTC(), Tapchis.getSoBPHTC(),Tapchis.getSoPHTC(),Tapchis.getThangPHTC()});
        }
        
    }//GEN-LAST:event_BtnRefreshActionPerformed

    private void BtnThemTapChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemTapChiActionPerformed
        // TODO add your handling code here:
        new ThemTapchi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnThemTapChiActionPerformed

    private void BtnXoaTapChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaTapChiActionPerformed
        // TODO add your handling code here:
        int row = TableTapChi.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(ListTapChi.this, "Vui long chon hoc sinh truoc", "loi",JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm = JOptionPane.showConfirmDialog(ListTapChi.this,"Ban chac chan muon xoa khong");
            
            if(confirm == JOptionPane.YES_OPTION){
                int MaTC = Integer.valueOf(String.valueOf(TableTapChi.getValueAt(row, 0)));
                
                service.deleteTapChi(MaTC);
            
                
             /// Xoa xong rooif refresh
            defaultTableModel.setRowCount(0);
            List<thuVien> tapchi = service.getALLTapChi();
            for(thuVien Tapchis : tapchi){
            defaultTableModel.addRow(new Object[]{Tapchis.getMaTC(), Tapchis.getTenTC(),Tapchis.gettenNXBTC(), Tapchis.getSoBPHTC(),Tapchis.getSoPHTC(),Tapchis.getThangPHTC()});
        }
            }
        }
    }//GEN-LAST:event_BtnXoaTapChiActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBackTapChi;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSuaTapChi;
    private javax.swing.JButton BtnThemTapChi;
    private javax.swing.JButton BtnXoaTapChi;
    private javax.swing.JTable TableTapChi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
